# Basic tutorial for classifying MINST digits

This is the basic tutorial for training the model (Moroney, 2021).

In [2]:
import tensorflow as tf #importing tensorflow
data = tf.keras.datasets.mnist #accessing the data for the digit classification

In [3]:
(training_images, training_labels), (test_images, test_labels) = data.load_data() #returns training and test sets

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
#print((training_images[0]))
#print((training_labels[0]))
#print((test_images[0]))
#print((test_labels[0]))
print(training_images.dtype)#checking the data type contained in each structure as well as the contents to check if all information is contained as described.
print(training_labels.dtype)
print(test_images.dtype)
print(test_labels.dtype)

uint8
uint8
uint8
uint8


In [5]:
training_images = training_images/255.0
test_images = test_images/255.0 #All pics are grayscale (0-255). This normalizes the images (sets between 0 and 1)

In [11]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [12]:
model.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [13]:
model.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8793 - loss: 0.4286
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 6ms/step - accuracy: 0.9673 - loss: 0.1135
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9779 - loss: 0.0744
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9837 - loss: 0.0546
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9877 - loss: 0.0407


In [14]:
model.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9721 - loss: 0.0840


[0.07441890239715576, 0.9757999777793884]

In [15]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten_1 (Flatten)                  │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_51 (Dense)                     │ (None, 128)                 │         100,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_52 (Dense)                     │ (None, 10)                  │           1,290 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 305,312 (1.16 MB)

 Trainable params: 101,770 (397.54 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 203,542 (795.09 KB)

These results are consistent with the literature regarding the use of artifical neural networks in the classification of the MINST digits dataset. Beohar and Rasool (2021) found that their model demonstrated a 0.96150 test accuracy rate after 5 epochs, which is slightly lower than the test accuracy shown here. An et al. (2020) and Islam et al. (2017) both found a 99% test accuracy rate utilizing an artificial neural network.

## Confusion matrix

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix
import numpy as np
prediction = model.predict(test_images)
confusion = confusion_matrix(test_labels, np.argmax(prediction,axis=1))
print(confusion)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
[[ 961    0    1    1    2    3    3    2    3    4]
 [   0 1125    3    1    0    0    1    1    4    0]
 [   2    1 1003    5    2    0    2    4   12    1]
 [   0    0    1  995    0    3    0    3    5    3]
 [   0    0    4    1  952    0    3    3    1   18]
 [   3    0    0   16    2  863    1    1    4    2]
 [   4    3    3    1    7    7  926    0    7    0]
 [   0    3   11    1    2    1    0  998    3    9]
 [   1    0    1    8    5    5    0    5  942    7]
 [   1    2    0    6    5    1    0    3    2  989]]


The model demonstrates particular issues with identifying other numbers as 9, which is consistent with other patterns of behavior in Shamsuddin et al. (2019).

After this basic case, it is prudent to check that the high accuracy of the model is actually based on the model running as expected. As such, this next case will test how the model runs with only one neuron.

# Verifying model efficacy

## One neuron

In [ ]:
model_test_0 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(1, activation = tf.nn.relu), #1 neuron
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

In [ ]:
model_test_0.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model_test_0.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.1886 - loss: 2.1035
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 1ms/step - accuracy: 0.2461 - loss: 1.8085
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.2639 - loss: 1.7481
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.2906 - loss: 1.7238
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - accuracy: 0.3058 - loss: 1.7062


In [ ]:
model_test_0.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.3106 - loss: 1.7484


[1.7085517644882202, 0.3140999972820282]

The model is evaluated at about 30% accuracy on the test data, which is higher than expected. Given 1 neuron, one would probably expect about 10% accuracy since the number of classes is 10, if the neuron operates at true random chance. <br><br>Note that the data type and content of the training images and labels as well as the test images and labels were checked in the tutorial section to verify that everything contained in those structures was aligned with their expected data type and content.

### Confusion matrix

In [ ]:
import numpy as np
from sklearn.metrics import confusion_matrix
import numpy as np
prediction = model_test_0.predict(test_images)
confusion = confusion_matrix(test_labels, np.argmax(prediction,axis=1))
print(confusion)

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[   0  875   30    5    9    0    3   49    1    8]
 [   0 1095   24    5    1    0    1    7    2    0]
 [   0  862   52    3   10    0    9   76    0   20]
 [   0  943   28    1    1    0    2   32    0    3]
 [   0    5    9    0  355    0  239  174    0  200]
 [   0  758   71    4    5    0    5   45    0    4]
 [   0   24   20    0   58    0  773   52    4   27]
 [   0   46   48    3   94    0   20  617    0  200]
 [   0  791   84    7    5    0    4   74    4    5]
 [   0   32   18    1  354    0  162  198    0  244]]


This may explain why the model is not performing as expected with only 1 neuron. The model overpredicts 1, identifying 0, 2, 3, 5, and 8 as 1 in a significant number of predictions. This could be due to some overarching similarities in the structures of the numbers. Additionally, it is likely that some pattern recognition of broadly applicable structure is occurring that might also contribute to the higher than chance accuracy. <br><br>

Shamsuddin et al. found that structural similarities across numbers may have caused differing label classifications even when used with a convolution neural network, though with a significantly lower error rate than the one demonstrated here.

## 5 neurons

In [ ]:
model_test_1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(5, activation = tf.nn.relu), #5 neurons
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model_test_1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model_test_1.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.6216 - loss: 1.1737
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.8480 - loss: 0.5203
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8579 - loss: 0.4793
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.8635 - loss: 0.4690
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.8668 - loss: 0.4531


In [ ]:
model_test_1.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.8508 - loss: 0.5127


[0.46310660243034363, 0.8686000108718872]

Now I have added additional neurons to see if there is improvement as the middle layer increases from 1 neuron. I expect to see improvement as the number goes up, if the model is behaving as expected.

## 10 neurons

In [ ]:
model_test_2 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(10, activation = tf.nn.relu), #10 neurons
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model_test_2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model_test_2.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7486 - loss: 0.8750
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9162 - loss: 0.2946
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.9244 - loss: 0.2639
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9296 - loss: 0.2443
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 2ms/step - accuracy: 0.9315 - loss: 0.2370


In [ ]:
model_test_2.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9187 - loss: 0.2761


[0.24676252901554108, 0.9284999966621399]

With 10 neurons, we reach 91% accuracy -- a 6% increase compared to the previous model with 5 neurons.

## 50 neurons

In [ ]:
model_test_3 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(50, activation = tf.nn.relu), #50 neurons
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

In [ ]:
model_test_3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model_test_3.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8536 - loss: 0.5200
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - accuracy: 0.9496 - loss: 0.1749
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9651 - loss: 0.1203
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9718 - loss: 0.0960
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.9759 - loss: 0.0783


In [ ]:
model_test_3.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9650 - loss: 0.1119


[0.09526697546243668, 0.9711999893188477]

Again, a gradual improvement is shown as the middle layer increases in number of neurons. This is generally consistent with the behavior demonstrated in the literature.

# Adding epochs and layers

## 50 epochs




At the suggestion of the book, I have trained the model for 50 epochs instead of 5. It is expected that this might cause overfitting. It is important to note that the text finds a dramatic improvement on accuracy on the training set and a smaller one for the test set when increasing the number of epochs.

In [ ]:
model1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

In [ ]:
model1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model1.fit(training_images, training_labels, epochs = 50)#training for 50 epochs instead

Epoch 1/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9990 - loss: 0.0031
Epoch 2/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9993 - loss: 0.0021
Epoch 3/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9988 - loss: 0.0042
Epoch 4/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9993 - loss: 0.0022
Epoch 5/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 3ms/step - accuracy: 0.9991 - loss: 0.0023
Epoch 6/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9996 - loss: 0.0012
Epoch 7/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9993 - loss: 0.0021
Epoch 8/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9999 - loss: 6.4197e-04
Epoch 9/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9985 - loss: 0.0048
Epoch 10/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9993 - loss: 0.0026
Epoch 11/50
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 1.0000 - loss: 1.5570e-04
Epoch 12/50
1875/1

In [ ]:
model1.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9763 - loss: 0.2778


Note that the gap between the training accuracy after the 50th epoch and the test accuracy is about 0.0238. Even though the accuracy for the test data has increased relative to the initial case with only 5 epochs, the gap between the training accuracy and test accuracy indicates that the model is overfit to the training data.

## Additional layers

## 2 middle layers

In [ ]:
model2_test_0 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model2_test_0.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model2_test_0.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.8885 - loss: 0.3886
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9707 - loss: 0.0973
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9790 - loss: 0.0648
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9850 - loss: 0.0467
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9877 - loss: 0.0380


In [ ]:
model2_test_0.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9715 - loss: 0.1005


[0.08630684018135071, 0.9765999913215637]

## 3 middle layers

In [ ]:
model2_test_1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model2_test_1.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model2_test_1.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8787 - loss: 0.3978
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9675 - loss: 0.1015
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9784 - loss: 0.0688
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9837 - loss: 0.0519
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9865 - loss: 0.0421


In [ ]:
model2_test_1.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9731 - loss: 0.0973


[0.0804683268070221, 0.9775999784469604]

## 4 middle layers

In [ ]:
model2_test_2 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

In [ ]:
model2_test_2.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model2_test_2.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.8715 - loss: 0.4208
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9668 - loss: 0.1087
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9751 - loss: 0.0758
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 13s 5ms/step - accuracy: 0.9817 - loss: 0.0571
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9848 - loss: 0.0481


In [ ]:
model2_test_2.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9655 - loss: 0.1115


[0.10092836618423462, 0.9688000082969666]

## 5 middle layers

In [ ]:
model2_test_3 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

In [ ]:
model2_test_3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model2_test_3.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.8567 - loss: 0.4482
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9644 - loss: 0.1160
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9749 - loss: 0.0850
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9799 - loss: 0.0677
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9834 - loss: 0.0543


In [ ]:
model2_test_3.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9688 - loss: 0.1158


[0.10084337741136551, 0.972000002861023]

## 10 middle layers

In [ ]:
model2_test_4 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model2_test_4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model2_test_4.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 16s 7ms/step - accuracy: 0.8151 - loss: 0.5582
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - accuracy: 0.9551 - loss: 0.1625
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 21s 6ms/step - accuracy: 0.9688 - loss: 0.1195
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 20s 6ms/step - accuracy: 0.9739 - loss: 0.0975
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 23s 8ms/step - accuracy: 0.9778 - loss: 0.0877


In [ ]:
model2_test_4.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9585 - loss: 0.1672


[0.14205369353294373, 0.9639999866485596]

## 50 middle layers

In [6]:
model2_test_5 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.relu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(128, activation = tf.nn.relu),
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [7]:
model2_test_5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [8]:
model2_test_5.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 57s 20ms/step - accuracy: 0.1125 - loss: 2.3016
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 38s 19ms/step - accuracy: 0.1128 - loss: 2.3013
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 47s 22ms/step - accuracy: 0.1116 - loss: 2.3015
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 37s 20ms/step - accuracy: 0.1112 - loss: 2.3013
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 40s 20ms/step - accuracy: 0.1125 - loss: 2.3015


In [9]:
model2_test_5.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.1160 - loss: 2.3009


[2.3011369705200195, 0.11349999904632568]

In [10]:
model2_test_5.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ flatten (Flatten)                    │ (None, 784)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 128)                 │         100,480 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_8 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_9 (Dense)                      │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_10 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_11 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_14 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_17 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_18 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_19 (Dense)                     │ (None, 128)                 │          16,512 │
├──────────────────────────────────────┼─────────────────────────────┼──────────────

 Total params: 2,732,576 (10.42 MB)

 Trainable params: 910,858 (3.47 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 1,821,718 (6.95 MB)

As layer number increased, it appears to reach a layer density at which accuracy begins to decrease compared to previous models with fewer layers.

# Activation function comparison

## Scaled exponential linear

Retraining with a different activation model (scaled exponential linear) than the tutorial.

In [ ]:
model0 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.nn.selu), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model0.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model0.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.8683 - loss: 0.4451
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 3ms/step - accuracy: 0.9481 - loss: 0.1760
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9664 - loss: 0.1126
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9751 - loss: 0.0839
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9810 - loss: 0.0637


In [ ]:
model0.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9693 - loss: 0.0961


[0.0832858458161354, 0.973800003528595]

This does slightly worse.

## Exponential

In [ ]:
model3 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.keras.activations.exponential), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model3.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model3.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8782 - loss: 0.4085
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9646 - loss: 0.1174
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9764 - loss: 0.0809
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9811 - loss: 0.0596
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9827 - loss: 0.0584


In [ ]:
model3.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9695 - loss: 0.1153


[0.09544801712036133, 0.973800003528595]

## Mish

In [ ]:
model4 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.keras.activations.mish), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model4.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model4.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8730 - loss: 0.4378
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9618 - loss: 0.1301
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.9769 - loss: 0.0764
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9836 - loss: 0.0530
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 4ms/step - accuracy: 0.9889 - loss: 0.0367


In [ ]:
model4.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9746 - loss: 0.0898


[0.07519776374101639, 0.9790999889373779]

## Linear

With the acknowledgement that a linear activation function is not generally advised, it is tested here to see if it produces a notable decrease in the test accuracy and to quantify that decrease in this particular problem.

In [ ]:
model5 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.keras.activations.linear), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model5.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model5.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 3ms/step - accuracy: 0.8642 - loss: 0.4683
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9158 - loss: 0.2951
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9203 - loss: 0.2848
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9230 - loss: 0.2824
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9242 - loss: 0.2691


In [ ]:
model5.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9078 - loss: 0.3282


[0.28512123227119446, 0.9204000234603882]

## Sigmoid

This activation function was also ill-advised according to the literature (Glorot and Bengio, 2010).

In [ ]:
model6 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)), #input layer specification
    tf.keras.layers.Dense(128, activation = tf.keras.activations.linear), #128 refers to neurons --> more means it runs slowly --> middle layer
    tf.keras.layers.Dense(10, activation = tf.nn.softmax)  #output layer --> 10 neurons bc 10 classes (0-9)
]) #defining the neural network

/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
model6.compile(optimizer = 'adam', loss = 'sparse_categorical_crossentropy', metrics = ['accuracy']) #specify loss function and the optimizer

In [ ]:
model6.fit(training_images, training_labels, epochs = 5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.8636 - loss: 0.4742
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9145 - loss: 0.3048
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 3ms/step - accuracy: 0.9193 - loss: 0.2896
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9191 - loss: 0.2886
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - accuracy: 0.9235 - loss: 0.2746


In [ ]:
model6.evaluate(test_images, test_labels) #evaluate model based on test images

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9055 - loss: 0.3394


[0.29311472177505493, 0.9186999797821045]

# References
An, S., Lee, M., Park, S., Yang, H., & So, J. (2020). An ensemble of simple convolutional neural network models for mnist digit recognition. arXiv preprint arXiv:2008.10400.<br><br>
Beohar, D., & Rasool, A. (2021, March). Handwritten digit recognition of MNIST dataset using deep learning state-of-the-art artificial neural network (ANN) and convolutional neural network (CNN). In 2021 International conference on emerging smart computing and informatics (ESCI) (pp. 542-548). IEEE.<br><br>
Geron, Aurelien. (2023). Hands-on machine learning with scikit-learn, keras, and tensorflow. O’Reilly Media.<br><br>
Glorot, X., & Bengio, Y. (2010, March). Understanding the difficulty of training deep feedforward neural networks. In Proceedings of the thirteenth international conference on artificial intelligence and statistics (pp. 249-256). JMLR Workshop and Conference Proceedings.<br><br>
Islam, K. T., Mujtaba, G., Raj, R. G., & Nweke, H. F. (2017, September). Handwritten digits recognition with artificial neural network. In 2017 International Conference on Engineering Technology and Technopreneurship (ICE2T) (pp. 1-4). IEEE.<br><br>
Moroney, Laurence. (2021). AI and machine learning for coders. O’Reilly Media.<br><br>
Shamsuddin, M. R., Abdul-Rahman, S., & Mohamed, A. (2019). Exploratory analysis of MNIST handwritten digit for machine learning modelling. In Soft Computing in Data Science: 4th International Conference, SCDS 2018, Bangkok, Thailand, August 15-16, 2018, Proceedings 4 (pp. 134-145). Springer Singapore.
